# Generated by Django 3.0.5 on 2020-04-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user_id',
            new_name='user',
        ),
    ]
