# Generated by Django 3.0.5 on 2020-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200416_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
